export { ReactComponent as SunIcon } from './sun.svg'
export { ReactComponent as MoonIcon } from './moon.svg'
export { ReactComponent as InfoIcon } from './info.svg'
export { ReactComponent as ErrorIcon } from './error.svg'
export { ReactComponent as SuccessIcon } from './success.svg'
export { ReactComponent as WarningIcon } from './warning.svg'
export { ReactComponent as CloseIcon } from './close-x.svg'
